version: '3.4'
services:
  golinkcut:
    entrypoint: /go/bin/golinkcut --memory
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: final
    ports:
      - "8080:8080"
      - "50051:50051"